# Generated by Django 3.2.7 on 2021-11-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
